export enum Role {
  Student = "Student",
  Officer = "Admission Officer",
  Admin = "Admin",
  Mentor = "Mentor"
}

export enum ApplicationStatus {
  Submitted = "Application Submitted",
  Verification = "Document Verification",
  Eligibility = "Eligibility Check",
  Counselling = "Counselling Allocation",
  Payment = "Fee Payment",
  Confirmed = "Admission Confirmed",
  Rejected = "Application Rejected"
}

export enum DocumentType {
  Aadhar = "Aadhar Card",
  SSC = "SSC Marks Sheet",
  Intermediate = "Intermediate Marks Sheet",
  TransferCertificate = "Transfer Certificate",
  IncomeCertificate = "Income Certificate",
  CasteCertificate = "Caste Certificate",
  PassportPhoto = "Passport Photo"
}

export enum VerificationStatus {
  Pending = "Pending",
  Valid = "Valid",
  Missing = "Missing",
  Duplicate = "Duplicate",
  Blurred = "Blurred",
  Rejected = "Rejected"
}

export interface VerificationDocument {
  id: string;
  type: DocumentType;
  name: string;
  status: VerificationStatus;
  url: string;
  remarks?: string;
  confidenceScore?: number; // percentage verified by AI
  verifiedAt?: string;
}

export interface StudentProfile {
  fullName: string;
  email: string;
  phone: string;
  address: string;
  gender: string;
  category: string;
  reservation: string;
  sscMarks: number;
  interMarks: number;
  entranceScore: number;
  selectedCourse: string;
  registrationId: string;
  avatarUrl?: string;
  sscBoard?: string;
  interBoard?: string;
}

export interface ApplicationForm {
  personalDetails: {
    fullName: string;
    email: string;
    phone: string;
    dob: string;
    gender: string;
    category: string;
    reservation: string;
  };
  academicDetails: {
    sscMarks: number;
    sscBoard: string;
    interMarks: number;
    interBoard: string;
    entranceName: string;
    entranceScore: number;
  };
  addressDetails: {
    street: string;
    city: string;
    state: string;
    zipCode: string;
  };
  courseSelection: {
    course: string;
    pref2?: string;
    pref3?: string;
  };
  documents: {
    [key in DocumentType]?: {
      url: string;
      name: string;
      status: VerificationStatus;
      confidence?: number;
      remarks?: string;
    };
  };
  isDraft: boolean;
  submittedAt?: string;
}

export interface Notification {
  id: string;
  title: string;
  content: string;
  timestamp: string;
  read: boolean;
  type: "info" | "success" | "warning" | "error";
}

export interface ChatMessage {
  id: string;
  sender: "user" | "ai" | "system";
  content: string;
  timestamp: string;
  audio?: string; // base64 audio if speech generation used
  suggestions?: string[];
}

export interface CRMLead {
  id: string;
  name: string;
  email: string;
  phone: string;
  score: number; // Lead score (0-100) generated by AI
  source: string; // e.g. Web, Referral, Campaign
  stage: "Lead" | "Contacted" | "Prospect" | "Applicant" | "Enrolled" | "Nurturing";
  lastActivity: string;
  owner: string;
  tasks: CRMTask[];
}

export interface CRMTask {
  id: string;
  title: string;
  dueDate: string;
  status: "Completed" | "Pending" | "Overdue";
  type: "Call" | "Email" | "Meeting" | "Task";
}

export interface CourseData {
  id: string;
  name: string;
  code: string;
  department: string;
  duration: string;
  intake: number;
  filled: number;
  fee: number;
  minEligibility: string;
}

export interface FacultyMember {
  id: string;
  name: string;
  department: string;
  email: string;
  role: string;
  assignedStudentsCount: number;
}
